{
 "title": "Messaging Metrics",
 "tags": [ "messaging" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Email Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(email_requests_total[5m])", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Message Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(consumed_messages_total[5m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Email Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(email_send_seconds_sum[5m]) / rate(email_send_seconds_count[5m])",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Email Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(email_errors_total[5m])", "legendFormat": "{{category}}" }
   ]
  }
 ]
}